### ISSUE TITLE
Version on PyPi is still the old one (0.1.1)

### ISSUE THREAD

**Issue by lstep** [gbour/PyAjam#2]
On PyPi, the latest version available (https://pypi.python.org/pypi/PyAjam/0.1.1) is still the one that needs 4XML :-1: 
An update to the site would be nice!

**Comment by gbour** [comment]
thanks for the notice @lstep, I'll update that

**Comment by gbour** [comment]
done, see https://pypi.python.org/pypi/PyAjam/0.2
